// <auto-generated />
using System;
using LavenderSpiritAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LavenderSpiritAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251005003015_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LavenderSpiritAPI.Models.EventUser", b =>
                {
                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("VolunteerId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("EventUsers");
                });

            modelBuilder.Entity("LavenderSpiritAPI.Models.LavEvent", b =>
                {
                    b.Property<Guid>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrgID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OrganizationOrgID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EventID");

                    b.HasIndex("OrgID");

                    b.HasIndex("OrganizationOrgID");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("LavenderSpiritAPI.Models.Organization", b =>
                {
                    b.Property<Guid>("OrgID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrgID");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("LavenderSpiritAPI.Models.Voluntree", b =>
                {
                    b.Property<Guid>("VoluntreeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VoluntreeID");

                    b.ToTable("Voluntrees");
                });

            modelBuilder.Entity("LavenderSpiritAPI.Models.EventUser", b =>
                {
                    b.HasOne("LavenderSpiritAPI.Models.LavEvent", "Event")
                        .WithMany("EventUsers")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LavenderSpiritAPI.Models.Voluntree", "Voluntree")
                        .WithMany("EventUsers")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Voluntree");
                });

            modelBuilder.Entity("LavenderSpiritAPI.Models.LavEvent", b =>
                {
                    b.HasOne("LavenderSpiritAPI.Models.Organization", "Org")
                        .WithMany()
                        .HasForeignKey("OrgID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LavenderSpiritAPI.Models.Organization", null)
                        .WithMany("HostedEvents")
                        .HasForeignKey("OrganizationOrgID");

                    b.Navigation("Org");
                });

            modelBuilder.Entity("LavenderSpiritAPI.Models.LavEvent", b =>
                {
                    b.Navigation("EventUsers");
                });

            modelBuilder.Entity("LavenderSpiritAPI.Models.Organization", b =>
                {
                    b.Navigation("HostedEvents");
                });

            modelBuilder.Entity("LavenderSpiritAPI.Models.Voluntree", b =>
                {
                    b.Navigation("EventUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
